### ISSUE TITLE
bug with display on custom saving example / documentation build never fails

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/pyDeltaRCM#181]
The rendered documentation: https://deltarcm.org/pyDeltaRCM/examples/custom_saving.html

does not include the example source code. I think the directives under `doctest` are wrong (https://github.com/DeltaRCM/pyDeltaRCM/runs/2237426803?check_suite_focus=true#step:6:88).

Our documentation build is not correctly failing anymore, which is why this was not caught...

**Comment by elbeejay** [comment]
Good catch regarding that rendered example. 

From what I can tell, in that PR the directive `:context:` given to `:doctest::` is just invalid, and for whatever reason the doctest extension throws a warning in that case instead of an error. When I've altered and broken the contents of the doctest blocks locally I am getting a proper error and the docs do not finish building during `make docs`. 

This seems to have happened because I was mixing the doctest and plot directives. Moving forward we should probably just stick to one for a given documentation file and that should help minimize these type of bugs.

**Comment by amoodie** [comment]
Yeah, the `:context:` is a `pyplot` directive thing. `doctest` has context by default. It is messy using both, I agree, we should try to not mix them within a file.

To be clear though, your pr #182 does not fix the failing-ness of the docs build on CI, right? I can open a new issue with just that bug, since they are actually separate issues.

**Comment by elbeejay** [comment]
> To be clear though, your pr #182 does not fix the failing-ness of the docs build on CI, right?

It does not.

But I think the build didn't fail because a *warning* as opposed to an *error* was raised by doctest. When an actual *error* is encountered the `doctest` call in the Makefile will break the build.
