### ISSUE TITLE
document stratigraphy methods

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/pyDeltaRCM#43]
Document and describe the routine for computing stratigraphy in `record_stratigraphy` method. 

Explain how this is different than what is called when the model is updated during the run? Which routine does that updating?

Document the other stratigraphy functions too?

This will help me implement the same type of strata in the DeltaMetrics project.

**Comment by elbeejay** [comment]
Short summary of how stratigraphy was handled in original DeltaRCM Matlab code:

1. Full 3D stratigraphy array is initialized with depth based on sea level and rise, subsidence and cell size

2. The z-values which correspond to the active surface are tracked via a `topz` 2D array during the model run to guide 'depth' at which values are placed in the stratigraphy array

3. Sand fraction values for locations in XY space are tracked via a `sand_frac` 2D array to set the actual values that end up in the stratigraphy array (initialized as 0.5, so the bottom layer of stratigraphy actually has all 0.5 values except where new sediment is introduced)

Just want to keep that framework in mind as I get through the way stratigraphy is handed in the Python implementation -- it looks like some alterations have been made to prioritize speed (initialization of smaller `lil_matrix` stratigraphy rather than full block), and it has been broken into functions of course.

**Comment by elbeejay** [comment]
Wanted to summarize the current way stratigraphy is handled here, will update documentation/doc-strings later with more concise language.

## Stratigraphy functions

1. `init_stratigraphy()`: Initialization via `init_stratigraphy()` takes place after the rest of the variables and fields are initialized
2. `save_stratigraphy()`: During `output_data()` the function `save_stratigraphy()` is called, which records stratigraphic information to model parameters, this happens with a frequency of `save_dt` (not `dt` like other variables, notably the original Matlab DeltaRCM implementation was updating the sand fraction and stratigraphy arrays every timestep after the sediment routing)
3. `record_final_stratigraphy()`: Just before the netCDF4 file is closed in `finalize()`, the function `record_final_stratigraphy()` creates netCDF4 variables for stratigraphy and writes them to the file

## Stratigraphy related variables and fields

- `strata_counter`: used to keep track of the number of times stratigraphy information has been saved, and when this number exceeds the side of the pre-allocated sparse arrays, they are extended
- `n_steps`: Used to set the size of the sparse strata arrays, and they get extended by this much when needed
- `init_eta`: Copy of the original basin topography, used as baseline to difference the final topography from. This is created upon stratigraphy initialization, but really is not needed so long as `eta` itself is saved to the netCDF4 file. In that case the original `eta` at `t=0` could serve the same role
- `strata_sand_frac`: Has shape `(L*W, n_steps)`. Holds the sand fraction information. Sand fraction information is generated when `save_stratigraphy()` is called by creating a sparse array with positive values in locations sediment was deposited. The positive value is the sand fraction in a given location, calculated as `Vp_dep_sand / (Vp_dep_sand + Vp_dep_mud)`, meaning only the most recent timestep of depositional information is actually recorded. 
- `strata_eta`: Has shape `(L*W, n_steps)`. This holds the "stratigraphic topography" and is computed when `save_stratigraphy()` is called. Basically stores the difference in topography between that timestep and the original (`init_eta`) topo. So that really doesn't need to happen if the `eta` data is saved, this could be computed when post-processing model output. This field is ultimately reshaped and saved as `strata_depth`

## Brief overview of how old `strata_preprocess.py` worked

- Set the vertical spacing (dz) of strata cells, and define the maximum depth of strata
- Some array indexing tricks to only preserve oldest cross-cutting `strata_depth` value (similar to method now implemented in DeltaMetrics)
- Then does some flipping and image/polygon manipulation to plug in the sand fraction data from `strata_sand_frac`

## Going forward

- Seems like it would be reasonable to save stratigraphic sand fraction information every timestep, implementation started [here]( https://github.com/amoodie/pyDeltaRCM/tree/export_sand_frac)
- If that is done, then there is no good reason to save `strata_depth`, and instead `eta` should be automatically saved if stratigraphy saving is turned on
- The above steps could make it possible to treat stratigraphy like other model grids, removing the separate methods/functions that pertain to stratigraphy only right now (e.g. initialization, saving, special output to netCDF)
