### ISSUE TITLE
Clarify "time"

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/pyDeltaRCM#46]
Currently one of the yaml parameters is `timesteps` which is the number of timesteps that `delta.update()` runs for. However in `run_pyDeltaRCM.py` we also identify "time" when we wrap `delta.update()` in this loop:

```
for time in range(0,1):
   delta.update()
```

The relevant question/issue here is the following; should `delta.update()` be wrapped in a loop?

Seems like we can ditch that loop in favor of specifying the number of timesteps in the yaml, as we do, unless there is a reason one would want to have different 'time' values in different places (in which case the different 'times' need to be clarified).

**Comment by ericbarefoot** [comment]
This is a really good point, @elbeejay. The idea with putting in `timesteps` the way I did it in #31 was mostly to just hijack the current API to introduce a simpler way of running the model. As such, I think its probably a non-ideal solution. A better goal, I think, is to dimensionalize time, so that the user specifies a length of model run in real time units they want, and then we calculate the number of timesteps under the hood, and call `update()` accordingly. 

One thought is that we could make the primary user interface with the model the `update_until()` method, and make it so that update never gets called by the user in a loop at all.

**Comment by elbeejay** [comment]
> The idea with putting in `timesteps` the way I did it in #31 was mostly to just hijack the current API to introduce a simpler way of running the model. 

I liked the idea of specifying the timesteps in the yaml with all the other variables as opposed to doing it separately in the runscript. 

> As such, I think its probably a non-ideal solution. A better goal, I think, is to dimensionalize time, so that the user specifies a length of model run in real time units they want, and then we calculate the number of timesteps under the hood, and call `update()` accordingly.

I think this is fine, `timesteps` as a yaml parameter could remain (and eventually become an optional parameter after time is dimensionalized)

> One thought is that we could make the primary user interface with the model the `update_until()` method, and make it so that update never gets called by the user in a loop at all.

And yes I agree with this, would just drop that loop entirely.

**Comment by amoodie** [comment]
Hey folks. I think that the branch I've been working on a bit might already address some of these concerns -- or it is at least related to them. In preparation for more advanced yaml parsing, I refactored some of what Eric put together on the command line interface #31. I'll open a PR when I've got a few more things done and I update the docs, but you can see (and checkout) [the code here if you like](https://github.com/amoodie/pyDeltaRCM_WMT/tree/preprocessor) or the [diff here](https://github.com/DeltaRCM/pyDeltaRCM_WMT/compare/develop...amoodie:preprocessor).

In short, I have created a "high level" and "low level" API. The high level works from the command line as Eric nicely implemented: 
```bash
pyDeltaRCM --config config_file.yml
```
where the `.yml` must have timesteps specified to work from the high level API. Alternatively, `pyDeltaRCM --config config_file.yml --timesteps 2` would run the `.yml` for two timesteps. There is also a high-level python API that works as:

```python
pp = preprocessor.Preprocessor(input_file=config_file.yml, timesteps=2)
pp.run_jobs()
```
which would run the jobs defined by the `input_file` for two timesteps _each_.

I plan to implement the following:
* matrix expansion #32 
* an `ensemble: N` option to run the same config `N` times with different seeds
* the two can also be combined to produce many runs
* sending the job handling to a `preprocessor` allows us to use [mpi4py](https://mpi4py.readthedocs.io/en/stable/) to run jobs easily on multiple cores (clusters).


SO, this kind of gets rid of the need for the `run_pyDeltaRCM.py` script and the looping there, because it happens via the preprocessor. IMPORTANTLY, The logic of looping is ONLY part of the package high-level API, so that any user can still use the low-level api:

```python
delta = DeltaModel(input_file = os.path.join(os.getcwd(), 'tests', 'test.yaml'))

for time in range(0, 1):
    delta.update()

delta.finalize()
```
(I changed the name of the main model code to `DeltaModel` as we have discussed)

> A better goal, I think, is to dimensionalize time, so that the user specifies a length of model run in real time units they want, and then we calculate the number of timesteps under the hood, and call update() accordingly.

Yeah this sounds fine, and could become the new default behavior of the high-level API once we figure out how to do it.

> One thought is that we could make the primary user interface with the model the update_until() method, and make it so that update never gets called by the user in a loop at all.

Yeah, we can add that as a method, sure. It would basically just be:
```python
def update_until(self, _until):
    for _ in range(0, _until):
        self.update()
```
though, right? I don't think we should _drop_ `update()`, but I support also adding `update_until()`.

**Comment by ericbarefoot** [comment]
> In short, I have created a "high level" and "low level" API.

Exactly what we need.

> I plan to implement the following:
> - matrix expansion #32
> - an ensemble: N option to run the same config N times with different seeds
> - the two can also be combined to produce many runs
> - sending the job handling to a preprocessor allows us to use mpi4py to run jobs easily on multiple cores (clusters).

Wow, stoked to see this come to life. Doing easy parallel processing and ensembles would be great.

> SO, this kind of gets rid of the need for the `run_pyDeltaRCM.py` script and the looping there

Correct me if I'm wrong @elbeejay, but those scripts were not necessarily even in the original package. Basically the user would have to realize that this was the way to make the model work, and construct their own script like this. I say good riddance.

> I don't think we should drop `update()`

For sure, the way you wrote it in that snippet, @amoodie, the key would be calculating the `_until`. If time is dimensionalized, then `_until` is just the length of the time vector. So `.update()` should be the primary timestepping mechanism, but most interaction for users using the model as a stand-alone product would be the `.update_until()` where the actual dimensional time is given in the config. 

As a side note, it's likely that if we are going to support the BMI wrapper, the BMI interface will use the `.update()` method primarily, but will likely do a lot of querying and setting of other parameters, so the model is basically being controlled from the outside entirely differently, and being run one timestep at a time.

**Comment by elbeejay** [comment]
> > SO, this kind of gets rid of the need for the `run_pyDeltaRCM.py` script and the looping there
> 
> Correct me if I'm wrong @elbeejay, but those scripts were not necessarily even in the original package. Basically the user would have to realize that this was the way to make the model work, and construct their own script like this. I say good riddance.

The `run_pyDeltaRCM.py` script has sat in the same repository as pyDeltaRCM_WMT as far as I've been aware so I don't know that I agree with that assessment -- but I support removing it in light of proposed changes / the direction we're heading.

**Comment by amoodie** [comment]
I think this has been resolved with all the preprocessor updates, and especially with documentation from #98.

@elbeejay, can we close?

**Comment by elbeejay** [comment]
Yeah everything looks great time-wise :+1:
